### ISSUE TITLE
Footer of doc pages is outdated

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/documentation#40]
The footer of the docs.kytos.io pages are outdated, with links to nowhere and old repositories references.

**Comment by diraol** [comment]
This webpage is not handled on this repository, so I'm moving it to the right place. But thanks for the notice @renanrodrigo ! =)

**Comment by renanrodrigo** [comment]
OH sorry @diraol . I don't have access to the webpage, so posted it here ;)

**Comment by diraol** [comment]
@renanrodrigo actually the footer you were refeering to was not from `docs.kytos.io` but for `docs.kytos.io/<anything_non_empty>` (like https://docs.kytos.io/kytos/). In such case, you are right, it concerns this repository since it is something to be updated on the sphinx theme. I'm reopening this issue.

**Comment by diraol** [comment]
@beraldoleal how should we deal with the sphinx footer [for all projects]?

**Comment by beraldoleal** [comment]
@diraol Thiago should take care of this. I will talk with him today.

**Comment by diraol** [comment]
This was done on kytos/documentation#45.
